### ISSUE TITLE
team score bug

### ISSUE THREAD

**Issue by nasearle** [nasearle/fall-back#81]
if someone leaves their score is subtracted from the team score

**Comment by stevenwally** [comment]
Hey @nasearle! Cool if I take this bug? :)

**Comment by nasearle** [comment]
Go for it! :)

**Comment by stevenwally** [comment]
@nasearle Can you provide a little bit more context around the issue? When you say "might", do you mean that the score of the player that leaves is only intermittently subtracted from the overall team score? 

Also, does "leave" mean game over for that player? Or just closing the browser? (Or both?) 

Thanks so much for the info! If there are any steps for reproduction that you could provide, that would be awesome too :)

**Comment by nasearle** [comment]
I said 'might' in the original post just because I hadn't tested and wasn't sure. but now we're sure a player's score is permanently subtracted from the total team score (sum of all the individual player scores in that game) when their socket is disconnected (when they close the game or refresh the page).

You can recreate the bug by opening the game in multiple windows and joining as two or more different players, get a few points for each player by killing some baddies, and then closing out one of the windows and see that player score is subtracted from the team score in the other players' windows in the top left of the screen.

**Comment by DavidScales** [comment]
I think the total score is calculated from just looping the individual player scores. so if one drops off then so does the total. Might need to keep track of the total score on the server in the Game object instead

**Comment by stevenwally** [comment]
@nasearle @DavidScales thank you both for the great info! I'm going to look into this more later in the week, maybe this weekend. Work has got me a little crazy this week 😅

**Comment by DavidScales** [comment]
fixed by stevenwally 🥇  in #89
